audit:
  privacy:
    enabled: false
  security:
    enabled: true
    issuer-uri: ${AUDIT_JWT_ISSUER_URI}

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

logging:
  level:
    root: INFO
    com.zaxxer.hikari.pool.ProxyConnection: ERROR
    org.springframework.jdbc.core: WARN
    org.springframework.transaction.interceptor.TransactionInterceptor: OFF
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level correlationId=%X{correlationId:-unavailable} logger=%logger{36} message=%msg%n"
